# WEB
FROM node:latest as build-stage

WORKDIR /app

COPY ./vue-app/package*.json ./

RUN npm install

COPY ./vue-app .

RUN npm run build

FROM nginx as production-stage

COPY --from=build-stage /app/dist /app

COPY nginx.conf /etc/nginx/nginx.conf